export enum Screens {
  Authenticate = "Authenticate",
  NestedDashboard = "NestedDashboard",
  Dashboard = "Dashboard",
  Rychlost = "Rychlost",
  Pesnicka = "Pesnicka",
  PraktickaMatika = "PraktickaMatika",
  Dvor = "Dvor",
  Zviera = "Zviera",
  Hangman = "Hangman",
  NestedContacts = "NestedContacts",
  Contacts = "Contacts",
  Contact = "Contact",
  PresovDB = "PresovDB",
  Movies = "Movies",
}
